let suggestions = [
    "Soldes",
    "Homme",
    "Femme",
    "Bagues",
    "Nous découvrir",
    "La Dorée ",
    "La Magnifique",
    "L'Argentée",
    "L'argentée+",
    "La Votre",
    "L'Ancienne",
    "La Voiture",
    "Colliers",
    "Bracelets",
    "Acceuil",
];
